echo "Speaking..."
flite -voice rms -t "GGX GANG 777777777777777777777"
flite -voice slt -t "Ok NOw Wot. L_ 2? L_ 2? L_ TriHard"
flite -voice awb -t "Behind you monkaW. Spooky scary skeleton"
flite -voice awb -t "Change Da world...My final message. Goodbye...Trilililili"
flite -voice slt -t "Kucing disebut juga kucing domestik[3][4] atau kucing rumah (nama ilmiah: Felis silvestris catus atau Felis catus) adalah sejenis mamalia karnivora dari keluarga Felidae."
